### ISSUE TITLE
Fragment definitions inlining

### ISSUE THREAD

**Issue by alexeygolev** [orionsoft/atom-graphql-autocomplete#4]
Using apollo client you should be able to do this
```js
const fragments = gql`
  fragment Details on ContentType {
    ...DetailsEditor on ContentType
    ...DetailsViewer on ContentType
  }
  ${DetailsEditor.fragments.ContentType}
  ${DetailsViewer.fragments.ContentType}
`
```
However the plugin is annoyed with `${}`.
Error: 
```
Syntax Error GraphQL (6:3) Unexpected $

5:   }
6:   ${DetailsEditor.fragments.ContentType}
     ^
7:   ${DetailsViewer.fragments.ContentType}
: /Users/grumpyOldRussian/Documents/web-projects/med-yacht-sales/mys-cms-frontend/src/modules/content-type-editor/details/Details.js:12
```

**Comment by thebigredgeek** [comment]
Yes also seeing this issue.  Really agitating.  Will a fix be created?

**Comment by joelgriffith** [comment]
It's likely because this is a static analysis tool, and the inlining here implies a run-time (I don't think the autocomplete can/will run everything through a runtime to evaluate that gql call).

This autocomplete is using `codemirror`'s utilities under-the-hood, which is what GraphiQL uses as well, so if it doesn't work in that editor it won't work here for the time being.

**Comment by nicolaslopezj** [comment]
Maybe we could replace the ${fragment} to spaces before running the error check

**Comment by thebigredgeek** [comment]
Couldn't you simply follow the reference to the string, if it exists?
